// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vedscejwvaxdichinnaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlZHNjZWp3dmF4ZGljaGlubmFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NTA1NTYsImV4cCI6MjA3NjAyNjU1Nn0.8w2stN97mjLQU30WvPrgDbUDmu5-jfvovRbjD-XZwcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
